name: fractal
description: Fractal objects.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none


environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  frac:
    path: ../frac
  fractal_word:
    path: ../fractal_word
  fractal_base:
    path: ../fractal_base
  universal_file: ^1.0.0
  universal_io: ^2.2.2
  cross_file: ^0.3.3+4
  cross_file_image: ^1.0.0
  idb_shim: ^2.3.1
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
